### ISSUE TITLE
Expected size 256 but got size 128 for tensor number 1 in the list

### ISSUE THREAD

**Issue by Cococyh** [yiranran/QMUPD#2]
Your idea is so great！

But when I change the imgsize from 512 to 1024 I met this error:
File "/home/ubuntu/cyh/QMUPD/models/networks.py", line 856, in forward
    y1 = torch.cat([f1, input2], 1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 256 but got size 128 for tensor number 1 in the list.

**Comment by yiranran** [comment]
Sorry for late reply. When we conducted experiments, we set input image size to 512, so some of the parameters are fixed to fit this input size. I added a commit to adapt to image size 1024: [commit#5](https://github.com/yiranran/QMUPD/commit/f5858608d0e294f3d0e704e0e714f4fe1e2123d9)

But note that since the model is trained under input size 512*512, if you test using input size 1024*1024, it may not get results as good as 512*512.
